import random as rd

class generateName:
    gk2=['AD', 'BC', 'by', 'ha', 'he', 'it', 'me', 'my', 'of', 'oh', 'OK', 'or', 'to', 'we']
    gk3=['age', 'ago', 'aid', 'air', 'and', 'ant', 'the', 'the', 'are', 'art', 'ask', 'bag', 'bed', 'bee', 'big', 'bit', 'box', 'boy', 'bun', 'bus', 'bus', 'the', 'bye', 'cab', 'cap', 'car', 'cow', 'cup', 'dam', 'die', 'dip', 'dog', 'dot', 'due', 'egg', 'eye', 'fax', 'fee', 'fix', 'flu', 'fly', 'fog', 'fox', 'fry', 'fun', 'fur', 'gas', 'gay', 'god', 'gun', 'ham', 'hay', 'hen', 'her', 'hey', 'him', 'his', 'hot', 'hug', 'ice', 'ill', 'ink', 'inn', 'its', 'jam', 'jar', 'jaw', 'jet', 'job', 'jog', 'joy', 'key', 'kid', 'lap', 'law', 'leg', 'lid', 'lip', 'lot', 'mad', 'map', 'mat', 'May', 'mix', 'net', 'new', 'nod', 'nor', 'not', 'now', 'nur', 'off', 'oil', 'old', 'out', 'owe', 'pan', 'pea', 'pen', 'per', 'pet', 'pie', 'pig', 'pot', 'pub', 'rag', 'rat', 'raw', 'ray', 'rob', 'row', 'sad', 'sea', 'sex', 'she', 'shy', 'sir', 'six', 'sky', 'son', 'sun', 'tap', 'tax', 'ten', 'tin', 'ton', 'top', 'try', 'two', 'use', 'via', 'wag', 'war', 'wax', 'way', 'web', 'wet', 'who', 'yes', 'yet', 'you', 'zip', 'zoo']
    gk4=['acre', 'arch', 'area', 'army', 'atom', 'ball', 'bank', 'bank', 'base', 'bath', 'beam', 'bean', 'bear', 'beef', 'beer', 'bell', 'belt', 'bird', 'blow', 'boat', 'body', 'bone', 'boot', 'boss', 'bowl', 'bush', 'cake', 'case', 'case', 'cave', 'chef', 'city', 'claw', 'clay', 'club', 'coal', 'cock', 'coin', 'coke', 'corn', 'cost', 'crew', 'crop', 'cube', 'data', 'date', 'dawn', 'deal', 'deed', 'deer', 'desk', 'diet', 'dirt', 'dish', 'doll', 'door', 'drug', 'drum', 'duck', 'dusk', 'dust', 'duty', 'edge', 'exit', 'fact', 'fare', 'farm', 'file', 'fist', 'flag', 'food', 'fork', 'form', 'fuel', 'gale', 'game', 'gate', 'glue', 'goal', 'goat', 'golf', 'gown', 'gram', 'hair', 'hall', 'hand', 'hawk', 'hero', 'hill', 'hole', 'hour', 'idea', 'inch', 'jazz', 'jeep', 'joke', 'junk', 'kilo', 'king', 'kite', 'knee', 'lady', 'lake', 'lamb', 'lamp', 'lead', 'lift', 'lion', 'list', 'load', 'loaf', 'luck', 'make', 'meat', 'menu', 'mess', 'mile', 'mind', 'mist', 'moon', 'nail', 'navy', 'neck', 'news', 'noon', 'nose', 'pace', 'page', 'pain', 'pair', 'park', 'path', 'pear', 'pest', 'pile', 'pine', 'pint', 'pipe', 'pity', 'plug', 'poem', 'poet', 'pole', 'pond', 'pool', 'pork', 'port', 'quiz', 'race', 'rail', 'rank', 'rice', 'ring', 'road', 'rock', 'role', 'roof', 'room', 'root', 'rope', 'rose', 'sale', 'salt', 'sand', 'scar', 'seal', 'seat', 'seed', 'self', 'shoe', 'shot', 'show', 'side', 'sign', 'silk',  'skin', 'slip', 'soap', 'sock', 'sofa', 'soil', 'song', 'soul', 'soup', 'star', 'swim', 'tail', 'tank', 'tape', 'taxi', 'team', 'tear', 'tent', 'term', 'text', 'tomb', 'tree', 'trip', 'tube', 'tune', 'unit', 'vain', 'vase', 'vest', 'vice', 'view', 'visa', 'wage', 'wall', 'ward', 'weed', 'week', 'well', 'wine', 'wing', 'wire', 'wood', 'wool', 'word', 'worm', 'yard']
    gk5=['actor', 'adult', 'agent', 'alarm', 'album', 'alley', 'anger', 'angle', 'apple', 'arrow', 'award', 'basin', 'beach', 'beard', 'beast', 'belly', 'bingo', 'blood', 'bonus', 'booth', 'brain', 'brand', 'bread', 'break', 'brick', 'bride', 'broom', 'bunch', 'camel', 'canal', 'candy', 'chair', 'chaos', 'chart', 'cheek', 'chess', 'chest', 'chick', 'chips', 'choir', 'class', 'clerk', 'clock', 'cloth', 'cloud', 'coach', 'coast', 'comma', 'coral', 'court', 'cream', 'crime', 'death', 'depth', 'diary', 'dozen', 'drill', 'dryer', 'eagle', 'earth', 'elder', 'enemy', 'entry', 'error', 'essay', 'event', 'faith', 'fault', 'feast', 'fence', 'ferry', 'fever', 'field', 'fight', 'flame', 'flesh', 'floor', 'flour', 'franc', 'frost', 'fruit', 'glass', 'globe', 'glory', 'glove', 'goods', 'grade', 'grain', 'grape', 'graph', 'grass', 'grill', 'group', 'gruel', 'guard', 'guest', 'guide', 'habit', 'heart', 'hobby', 'honey', 'hotel', 'house', 'jeans', 'jewel', 'juice', 'laser', 'least', 'level', 'lorry', 'lunch', 'maple', 'march', 'match', 'match', 'means', 'medal', 'media', 'melon', 'model', 'money', 'month', 'motor', 'motto', 'mouth', 'movie', 'music', 'niece', 'night', 'noise', 'novel', 'nurse', 'nylon', 'ocean', 'opera', 'orbit', 'order', 'organ', 'owner', 'panda', 'paper', 'party', 'peace', 'peach', 'piano', 'piece', 'pilot', 'plane', 'plate', 'pound', 'power', 'price', 'pride', 'prize', 'pulse', 'pupil', 'purse', 'queen', 'queue', 'quilt', 'radio', 'razor', 'reply', 'river', 'robot', 'rugby', 'ruler', 'salad', 'scarf', 'scene', 'sense', 'shade', 'shame', 'shark', 'sheet', 'shine', 'shirt', 'shore', 'sight', 'skill', 'skirt', 'slave', 'sleep', 'slice', 'smell', 'snack', 'space', 'spade', 'spear', 'sport', 'squid', 'staff', 'stage', 'stain', 'stair', 'stamp', 'stand', 'state', 'steak', 'steam', 'steel', 'stone', 'store', 'storm', 'story', 'style', 'sugar', 'suite', 'sweat', 'sword', 'table', 'taste', 'theft', 'theme', 'thing', 'tiger', 'title', 'topic', 'towel', 'tower', 'trend', 'trick', 'troop', 'trunk', 'truth', 'uncle', 'union', 'value', 'video', 'waist', 'whale', 'wheat', 'wheel' , 'windy', 'works', 'world', 'wrist']
    gk6=['accent', 'action', 'advice', 'affair', 'agency', 'agenda', 'aspect', 'author', 'autumn', 'avenue', 'bakery', 'ballet', 'bamboo', 'banana', 'basket', 'battle', 'beauty', 'behalf', 'belief', 'blouse', 'border', 'bottle', 'bottom', 'bounce', 'boxing', 'branch', 'breast', 'breath', 'bridge', 'brunch', 'bucket', 'buffet', 'butter', 'camera', 'candle', 'carbon', 'carpet', 'castle', 'cattle', 'chance', 'change', 'cheese', 'choice', 'chorus', 'church', 'cinema', 'circus', 'clinic', 'coffee', 'comedy', 'cooker', 'cookie', 'corner', 'couple', 'course', 'cousin', 'cowboy', 'crayon', 'credit', 'custom', 'danger', 'decade', 'degree', 'desert', 'dinner', 'doctor', 'dollar', 'drawer', 'driver', 'editor', 'effect', 'effort', 'empire', 'ending', 'energy', 'engine', 'eraser', 'expert', 'family', 'farmer', 'father', 'fellow', 'finger', 'flower', 'forest', 'format', 'friend', 'fright', 'gallon', 'garage', 'garden', 'garlic', 'granny', 'grocer', 'ground', 'growth', 'guitar', 'hammer', 'health', 'heaven', 'height', 'helmet', 'hotdog', 'hunger', 'hunter', 'income', 'island', 'jacket', 'jungle', 'keeper', 'kettle', 'ladder', 'latter', 'lawyer', 'leader', 'league', 'length', 'lesson', 'letter', 'locust', 'manner', 'marble', 'market', 'member', 'memory', 'method', 'middle', 'minute', 'mirror', 'moment', 'monkey', 'mother', 'museum', 'mutton', 'nation', 'needle', 'noodle', 'number', 'office', 'opener', 'origin', 'outing', 'output', 'packet', 'paddle', 'palace', 'parcel', 'parcel', 'pardon', 'parent', 'parrot', 'patent', 'pencil', 'people', 'pepper', 'period', 'person', 'petrol', 'phrase', 'pillow', 'planet', 'player', 'plenty', 'pocket', 'police', 'policy', 'porter', 'potato', 'powder', 'prayer', 'prison', 'puzzle', 'rabbit', 'radium', 'recipe', 'relief', 'result', 'reward', 'rocket', 'runner', 'safety', 'sailor', 'salary', 'saucer', 'savage', 'saying', 'school', 'scores', 'scream', 'screen', 'season', 'second', 'secret', 'shaver', 'shorts', 'silver', 'singer', 'sister', 'sleeve', 'socket', 'speech', 'spirit', 'spring', 'spring', 'statue', 'status', 'strait', 'street', 'string', 'studio', 'summer', 'sunset', 'supper', 'tablet', 'tailor', 'tanker', 'teapot', 'temple', 'tennis', 'theory', 'thread', 'throat', 'ticket', 'tissue', 'tomato', 'viewer', 'violin', 'voyage', 'waiter', 'walnut', 'warmth', 'wealth', 'weight', 'window', 'winner', 'winter', 'wisdom', 'worker']

    def __init__(self,dic):
        #if dic=='gk':
        self.c=[self.gk2,self.gk3,self.gk4,self.gk5,self.gk6]
        self.lens=[len(self.gk2),len(self.gk3),len(self.gk4),len(self.gk5),len(self.gk6)]
        self.totalLens=5
		#self.c=[self.gk4,self.gk5,self.gk6]
        #self.lens=[len(self.gk4),len(self.gk5),len(self.gk6)]
        #self.totalLens=3



    def genIndex(self,genLens):
        ''' ((a1,b1),(a2,b2)....)'''
        dis=[]

        for i in xrange(genLens):
            a=rd.randint(0,self.totalLens-1)
            b=rd.randint(0,self.lens[a]-1)
            dis.append([a,b])
        return dis

    def getNames(self,genLens):

        dis=self.genIndex(genLens)
        names=''
        for i in xrange(genLens):
            names+=self.c[dis[i][0]][dis[i][1]]
        return names
